package MiniProject;

import javax.swing.*;
import java.awt.*;

public class SoccerApp {
    private JPanel MainFrame;


    public static void main(String[] args) {

        JFrame AppFrame = new JFrame("Soccer Booking System");

        SoccerApp gui = new SoccerApp();

        AppFrame.setSize(400, 350);
        AppFrame.setVisible(true);

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return MainFrame;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }
    //
}
